"""
This module is a rip-off of Docker's name generation procedure for 
containers, so it can be used in Python programs.  The first word
is an adjective, and the second word is the name of someone you
respect and admire or that has done something notable.  For the
purposes of this module, the theme is music and television
"""
from random import choice

LEFT_WORDS = [
    "abbreviated",
    "absolved",
    "accommodating",
    "aggravated",
    "alienated",
    "ambivalent",
    "aroused",
    "bamboozled",
    "belittled",
    "corroded",
    "cromulent",
    "dangerous",
    "deranged",
    "disinterested",
    "embiggened",  # it's a perfectly cromulent word
    "enlightened",
    "enraged",
    "frightening",
    "glorious",
    "gross",
    "high",
    "insane",
    "impractical",
    "innervated",
    "jesting",
    "joking",
    "jostled",
    "kingly",
    "knighted",
    "lamenting",
    "laminating",
    "limited",
    "lengthy",
    "lethargic",
    "lupine",
    "marred",
    "mended",
    "miniature",
    "nonplussed",
    "opposed",
    "practical",
    "quizzical",
    "quiescent",
    "quintessential",
    "romantic",
    "rugged",
    "simple",
    "slippery",
    "squirrelly",
    "supple",
    "tough",
    "tumultuous",
    "ubiquitous",
    "worried",
    "zinged",
]

RIGHT_WORDS = [
    "crow",
    "servo",
    "gypsy",
    "cambot",
    "hodgson",
    "nelson",
    "bobo",
    "brainguy",
    "forrester",
    "frank",
    "torgo",
    "tyler",
    "perry",
    "young",
    "johnson",
    "hetfield",
    "ulrich",
    "burton",
    "hammett",
    "mustaine",
    "menza",
    "gates",
    "vengeance",
    "shadows",
    "pert",
    "lee",
    "leifeson",
    "zanes",
    "osbourne",
    "butler",
    "iommi",
    "page",
    "plant",
    "bonham",
    "simmons",
    "stanley",
    "criss",
    "frehley",
    "araya",
    "king",
    "hanneman",
    "peaches",
    "white",
    "danzig",
    "only",
    "graves", 
    "frankenstein",
    "chudd",
    "rollins",
    "ramone",
    "vaughn",
    "belladonna",
    "ian",
    "white",
    "anthony",
    "roth",
    "haggar",
    "van_halen",
    "stallman",
    "hogan",
    "savage",
    "cena",
    "michaels",
    "helmsley",
    "flair",
    "borden",
    "luger",
    "nash",
    "hall",
]

def namegen():
    """
    Return a randomly generated name from the left and right lists, joined
    with an underscore
    """
    return "{0}_{1}".format(
        choice(LEFT_WORDS), choice(RIGHT_WORDS)
    )
